---
title: I.Learn
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/i.learn"
url: https://sdeehub.github.io/
theme_settings:
  title: i.learn
  avatar: assets/img/reallife_border_128x128.jpg
  favicon: assets/favicon.ico
  gravatar: 
  description: A Learning Journal Blog Posts | การจดบันทึกเรื่องที่เราเรียนรู้ในแต่ละวัน
  header_text: "<blockquote>Study the past if you would define the future. ~ Confucius</blockquote>\n"
  header_text_feature_image: assets/img/sample_feature_img.png
  footer_text: 'Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type
    Theme</a>

'
  rss: false
  email_address: 
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  gitlab: 
  github: sdeehub/i.learn
  google_plus: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  tumblr: 
  twitter: odd_daboss
  wordpress: 
  youtube: 
  google_analytics: 
  disqus_shortname: 
  katex: true
  search: false
  str_follow_on: Follow on
  str_rss_follow: Follow RSS feed
  str_email: Email
  str_next_post: Next
  str_previous_post: Prev
  str_next_page: Next
  str_previous_page: Prev
  str_continue_reading: Continue reading
  str_javascript_required_disqus: Please enable JavaScript to view comments.
  str_search_no_results: No results found.
  google_fonts: Athiti|Megrim|Prompt
  post_navigation: true
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
